name:                hsxtal
version:             0.1.0.0
github:              "githubuser/hsxtal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hsxtal#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- attoparsec-binary
- bytestring
- text
- vector
- binary
# For DB connection
- mysql-simple

library:
  source-dirs: src

executables:
  hsxtal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsxtal

tests:
  hsxtal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsxtal
